matrix:
  include:
    - language: go
      go:
        - 1.8
        - 1.9
        - master
      before_install:
        - sudo wget https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -O /usr/local/bin/dep && chmod 755 /usr/local/bin/dep
      install:
        - cd client/go && dep ensure
      script:
        - go test ./client/go ./client/go/model