sudo: required
matrix:
  include:

    - language: scala
      scala: 2.12.3
      jdk: oraclejdk8
      services:
        - docker
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot
      before_script:
        - sbt docker
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test

    - language: scala
      scala: 2.11.11
      jdk: oraclejdk8
      services:
        - docker
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot
      before_script:
        - sbt docker
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test

    - language: go
      go: 1.8
      before_install:
        - sudo wget https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -O /usr/local/bin/dep
        - sudo chmod +x /usr/local/bin/dep
      install:
        - cd $TRAVIS_BUILD_DIR/client/go && dep ensure
      script:
        - cd $TRAVIS_BUILD_DIR/client/go && go vet  . ./model
        - cd $TRAVIS_BUILD_DIR/client/go && go test . ./model

    - language: go
      go: 1.9
      before_install:
        - sudo wget https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -O /usr/local/bin/dep
        - sudo chmod +x /usr/local/bin/dep
      install:
        - cd $TRAVIS_BUILD_DIR/client/go && dep ensure
      script:
        - cd $TRAVIS_BUILD_DIR/client/go && go vet  . ./model
        - cd $TRAVIS_BUILD_DIR/client/go && go test . ./model