sudo: required
matrix:
  include:

    - language: scala
      scala: "2.12.6"
      jdk: oraclejdk8
      services:
        - docker
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot
      before_script:
        - sbt docker
      script:
        - sbt headerCheck
        - sbt ++$TRAVIS_SCALA_VERSION test

    - language: scala
      scala: "2.11.12"
      jdk: oraclejdk8
      services:
        - docker
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt/boot
      before_script:
        - sbt docker
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test

    - language: go
      go: "1.10"
      before_install:
        - sudo wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O /usr/local/bin/dep
        - sudo chmod +x /usr/local/bin/dep
        - mv $GOPATH/src/github.com/CyberAgent $GOPATH/src/github.com/cyberagent
        - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cyberagent/typebook
      install:
        - cd $TRAVIS_BUILD_DIR/client/go && dep ensure -v
        - cd $TRAVIS_BUILD_DIR/cli/tb && dep ensure -v
      script:
        - cd $TRAVIS_BUILD_DIR && go vet ./...
        - cd $TRAVIS_BUILD_DIR && go test ./...

    - language: go
      go: "1.9"
      before_install:
        - sudo wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O /usr/local/bin/dep
        - sudo chmod +x /usr/local/bin/dep
        - mv $GOPATH/src/github.com/CyberAgent $GOPATH/src/github.com/cyberagent
        - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cyberagent/typebook
      install:
        - cd $TRAVIS_BUILD_DIR/client/go && dep ensure -v
        - cd $TRAVIS_BUILD_DIR/cli/tb && dep ensure -v
      script:
        - cd $TRAVIS_BUILD_DIR && go vet ./...
        - cd $TRAVIS_BUILD_DIR && go test ./...

    - language: node_js
      node_js: "node"
      install:
        - cd $TRAVIS_BUILD_DIR/client/typescript && npm install
      script:
        - cd $TRAVIS_BUILD_DIR/client/typescript && npm run lint
        - cd $TRAVIS_BUILD_DIR/client/typescript && npm test
