
name: "typebook"
version: "0.1.0"
description: "An Avro schema registry"
keywords:
  - "avro"
  - "schema registry"
  - "MySQL backend"
  - "semantic versioning"
sources:
  - "https://avro.apache.org"
maintainers:
  - name: "saint1991"
    email: "saint.seiya.1122@gmail.com"
engine: "gotpl"
apiVersion: "1.0.0"
tillerVersion: "2.5.0"
