version: '3'

services:
  backend-db:
    image: "mysql:5.7.19"
    healthcheck:
      test: ["CMD", "mysql", "-e", "quit"]
      interval: "15s"
      timeout: "5s"
      retries: 5
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "typebook"
      MYSQL_USER: "typebook"
      MYSQL_PASSWORD: "typebook"
      MYSQL_DATABASE: "registry"
