apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mysql-user: {{ .Values.mysql.mysqlUser | b64enc | quote }}
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}